FROM acr-on-enterprise-registry.cn-hangzhou.cr.aliyuncs.com/on-common/nginx:1.25.3

ARG PACKAGE

WORKDIR /usr/share/nginx/html

RUN echo ${PACKAGE}
RUN wget ${PACKAGE} -O package.tgz
RUN tar xf package.tgz

COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
