FROM acr-on-enterprise-registry.cn-hangzhou.cr.aliyuncs.com/on-common/node:24.14.1

ARG PACKAGE

WORKDIR /app
 
RUN echo ${PACKAGE}
RUN wget ${PACKAGE} -O package.tgz
RUN tar xf package.tgz

EXPOSE 3000

CMD [ "npm", "run", "prod:api" ]